osx_image: xcode10.2
language: swift
os: osx
script:
  - xctool -workspace SoloLearnTask.xcworkspace -scheme SoloLearnTask -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace SoloLearnTask.xcworkspace -scheme SoloLearnTask -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
